### ISSUE TITLE
requirements.txt остутствует

### ISSUE THREAD

**Issue by frontalex** [Oknolaz/vasisualy-windows#2]
Его нету, взял из родительского, но сбилдить не удалось
 

> `Building wheels for collected packages: pyalsaaudio
  Building wheel for pyalsaaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\Downloads\vasisualy-windows-main\vasisualy-windows-main\env\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VR2\\AppData\\Local\\Temp\\pip-install-9mopjt77\\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\\setup.py'"'"'; __file__='"'"'C:\\Users\\VR2\\AppData\\Local\\Temp\\pip-install-9mopjt77\\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\VR2\AppData\Local\Temp\pip-wheel-vpggzyv8'
       cwd: C:\Users\VR2\AppData\Local\Temp\pip-install-9mopjt77\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'alsaaudio' extension
  creating build
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IE:\Downloads\vasisualy-windows-main\vasisualy-windows-main\env\include -IC:\Program Files\Python39\include -IC:\Program Files\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcalsaaudio.c /Fobuild\temp.win-amd64-3.9\Release\alsaaudio.obj
  alsaaudio.c
  alsaaudio.c(28): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: alsa/asoundlib.h: No such file or directory,
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pyalsaaudio
  Running setup.py clean for pyalsaaudio
Failed to build pyalsaaudio
Installing collected packages: pyalsaaudio, plyer, mss, geocoder
    Running setup.py install for pyalsaaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'E:\Downloads\vasisualy-windows-main\vasisualy-windows-main\env\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VR2\\AppData\\Local\\Temp\\pip-install-9mopjt77\\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\\setup.py'"'"'; __file__='"'"'C:\\Users\\VR2\\AppData\\Local\\Temp\\pip-install-9mopjt77\\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\VR2\AppData\Local\Temp\pip-record-xwby9m1a\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Downloads\vasisualy-windows-main\vasisualy-windows-main\env\include\site\python3.9\pyalsaaudio'
         cwd: C:\Users\VR2\AppData\Local\Temp\pip-install-9mopjt77\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\
    Complete output (11 lines):
    running install
    running build
    running build_ext
    building 'alsaaudio' extension
    creating build
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IE:\Downloads\vasisualy-windows-main\vasisualy-windows-main\env\include -IC:\Program Files\Python39\include -IC:\Program Files\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcalsaaudio.c /Fobuild\temp.win-amd64-3.9\Release\alsaaudio.obj
    alsaaudio.c
    alsaaudio.c(28): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: alsa/asoundlib.h: No such file or directory,
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\Downloads\vasisualy-windows-main\vasisualy-windows-main\env\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VR2\\AppData\\Local\\Temp\\pip-install-9mopjt77\\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\\setup.py'"'"'; __file__='"'"'C:\\Users\\VR2\\AppData\\Local\\Temp\\pip-install-9mopjt77\\pyalsaaudio_309a3fee2aa7431fbc5882422f17c1ff\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\VR2\AppData\Local\Temp\pip-record-xwby9m1a\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Downloads\vasisualy-windows-main\vasisualy-windows-main\env\include\site\python3.9\pyalsaaudio' Check the logs for full command output.`

**Comment by Oknolaz** [comment]
`requirements.txt` был добавлен с последним коммитом. Теперь проблем с этим быть не должно.
